Show page views in action=info
miraheze/MatomoAnalytics pull request #137
Opened 2024-10-22 01:46 UTC by AgentIsai

2024-10-22 04:32 UTC, Universal-Omega commented on includes/MatomoAnalyticsWiki.php
> +	// Visits by social network
What???

2024-10-22 04:33 UTC, Universal-Omega commented on includes/MatomoAnalyticsHooks.php
> +		$mA = new MatomoAnalyticsWiki( $context->getConfig()->get( 'DBname' ) );
MainConfigNames

2024-10-22 10:24 UTC, BlankEclair commented on includes/MatomoAnalyticsHooks.php
> +		$formatted = $lang->formatNum( $total );
Can be simplified with [`Message::numParams()`](https://doc.wikimedia.org/mediawiki-core/REL1_42/php/classMediaWiki_1_1Message_1_1Message.html#a49ede4e918e1f5834396ca41cae58c9d)

2024-10-23 01:17 UTC, Universal-Omega requested changes

2024-10-23 01:17 UTC, Universal-Omega commented on extension.json
> +			"class": "Miraheze\\MatomoAnalytics\\Hooks\\Handlers\\CreateWiki"
Use HookHandlers not Hooks\Handlers

2024-10-23 09:11 UTC, Universal-Omega commented on includes/MatomoAnalyticsWiki.php
> +		string $title = null
Technically this doesn't need `?`, however that does change behavior in PHP 8.4 where is does require to be explicitly nullable and = null doesn't make it implicit anymore (or at least deprecated) so yeah it definitely should be now for future support.

2024-10-23 14:00 UTC, BlankEclair approved these changes

2024-10-23 14:04 UTC, merged

2024-10-23 16:47 UTC, Universal-Omega commented on .github/workflows/mediawiki-tests.yml
> +          # Latest MediaWiki stable - PHP 8.2
This needs to be the same on all extensions so we should not be changing mediawiki-tests in extension PRs. Also 8.1 should be kept.

2024-10-23 16:47 UTC, Universal-Omega commented on .github/workflows/mediawiki-tests.yml
> +            keepdependencies: true
This isn't a valid option

2024-10-23 16:47 UTC, Universal-Omega commented on extension.json
> +	"version": "1.2.0",
CHANGELOG entry?

2024-10-23 16:47 UTC, Universal-Omega commented on i18n/en.json
> +	"matomoanalytics-count": "$1",
qqq entries?

2024-10-23 16:47 UTC, Universal-Omega commented on maintenance/cleanupMatomos.php
> +				$mA->deleteSite( $DBname );
Static function we shouldn't be using new MatomoAnalytics

2024-10-23 16:47 UTC, Universal-Omega commented on maintenance/modifyMatomo.php
> +			$mA->deleteSite( $DBname );
Static function we shouldn't be using new MatomoAnalytics

2024-10-23 16:47 UTC, Universal-Omega commented on maintenance/modifyMatomo.php
> +			$mA->addSite( $DBname );
Static function we shouldn't be using new MatomoAnalytics

2024-10-23 16:47 UTC, Universal-Omega commented on maintenance/addMissingMatomos.php
> +				$mA->addSite( $DBname );
Static function we shouldn't be using new MatomoAnalytics

2024-10-23 16:47 UTC, Universal-Omega commented on includes/HookHandlers/CreateWiki.php
> +		$mA->deleteSite( $dbname );
Static function we shouldn't be using new MatomoAnalytics

2024-10-23 16:47 UTC, Universal-Omega commented on includes/HookHandlers/CreateWiki.php
> +		$mA->renameSite( $old, $new );
Static function we shouldn't be using new MatomoAnalytics

2024-10-23 16:47 UTC, Universal-Omega commented on includes/HookHandlers/CreateWiki.php
> +		$mA->addSite( $dbname );
Static function we shouldn't be using new MatomoAnalytics