Add chart support
miraheze/MatomoAnalytics pull request #140
Opened 2024-10-24 19:23 UTC by AgentIsai

2024-10-24 19:46 UTC, Universal-Omega requested changes

2024-10-24 19:46 UTC, Universal-Omega commented on maintenance/modifyMatomo.php
> +	public function __construct( MatomoAnalytics $matomoAnalytics ) {
? You cant inject into a maintenance script?

2024-10-24 19:46 UTC, Universal-Omega commented on maintenance/cleanupMatomos.php
> +	public function __construct( MatomoAnalytics $matomoAnalytics ) {
? You cant inject into a maintenance script?

2024-10-24 19:46 UTC, Universal-Omega commented on maintenance/addMissingMatomos.php
> +	public function __construct( MatomoAnalytics $matomoAnalytics ) {
? You cant inject into a maintenance script?

2024-10-24 19:46 UTC, Universal-Omega commented on includes/SpecialAnalytics.php
> +		$out->addModules( [ 'ext.matomoanalytics.oouiform', 'ext.matomoanalytics.graphs' ] );
Each item on new line with trailing comma

2024-10-24 19:46 UTC, Universal-Omega commented on includes/MatomoAnalyticsViewer.php
> +		$html .= $mwHtml->element( 'canvas', [
Always use static methods when static here use Html::element.

2024-10-24 19:46 UTC, Universal-Omega commented on includes/MatomoAnalyticsViewer.php
> +use Html;
MediaWiki\Html\Html;

2024-10-24 19:46 UTC, Universal-Omega commented on includes/HookHandlers/CreateWiki.php
> +	public function __construct( MatomoAnalytics $matomoAnalytics ) {
MatomoAnalytics is not something that should be injected as is. It should a whlle different type of service class if we want to however I don't even think it is necessary. Just use the static methods.

2024-10-24 19:46 UTC, Universal-Omega commented on extension.json
> +				"chart.js",
naming scheme: ext.matomoanalytics.chart.js etc..

2024-10-26 07:29 UTC, BlankEclair commented on includes/SpecialAnalytics.php
> +		$out->addModules( [ 'ext.matomoanalytics.graphs' ] );
Can't this be in one array?

2024-10-26 07:29 UTC, BlankEclair commented on includes/MatomoAnalyticsViewer.php
> +	public function getAnalyticsCanvasHtml( string $type, string $chartType ) {
`$chartType` is unused (if this PR is a WIP, then perhaps it should be marked as a draft?)

2024-10-26 07:29 UTC, BlankEclair commented on includes/MatomoAnalyticsViewer.php
> +			'class' => 'matomoanalytics-chart matomoanalytics-chart-bar',
Instead of including the chart type as a class, perhaps we can use [custom data attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*)?

2024-10-26 07:29 UTC, BlankEclair commented on includes/MatomoAnalyticsViewer.php
> +		$html .= Html::element( 'canvas', [
Why a variable + concatenation when we could directly return the result of `Html::element()`?

2024-10-26 07:29 UTC, BlankEclair commented on modules/ext.matomoanalytics.graphs.js
> +    const data = {};
Why objects instead of arrays?

2024-10-26 07:29 UTC, BlankEclair commented on includes/MatomoAnalyticsViewer.php
> +			'id' => 'matomoanalytics-chart',
It is not recommended to have multiple HTML elements with the same `id`

2024-10-26 07:29 UTC, BlankEclair commented on includes/MatomoAnalyticsViewer.php
I wonder if we can have CSS to hide the canvas elements for no-Javascript users by selecting on `html.client-nojs`

2024-10-26 20:21 UTC, AgentIsai commented on includes/MatomoAnalyticsViewer.php
> +	public function getAnalyticsCanvasHtml( string $type, string $chartType ) {
This is almost basically a PoC. Not intended to resemble the final product at this stage.

2024-10-27 07:26 UTC, BlankEclair commented
(Unsubscribing from the PR, please rerequest review when you want me to check it or when this is out of draft)

2024-10-30 01:40 UTC, Universal-Omega requested changes
Just some initial review comments. Even though this is still draft.

2024-10-30 01:40 UTC, Universal-Omega commented on modules/ext.matomoanalytics.special.css
Should use LESS rather than CSS

2024-10-30 01:40 UTC, Universal-Omega commented on extension.json
> +			"targets": [ "desktop", "mobile" ]
No targets

2024-10-30 01:40 UTC, Universal-Omega commented on extension.json
> +			"targets": [ "desktop", "mobile" ]
No targets

2024-10-30 01:40 UTC, Universal-Omega commented on extension.json
>  			"targets": [ "desktop", "mobile" ],
No targets

2024-10-30 01:40 UTC, Universal-Omega commented on extension.json
>  			"targets": [ "desktop", "mobile" ],
No targets

2024-10-30 01:40 UTC, Universal-Omega commented on includes/MatomoAnalyticsViewer.php
> +			'class' => 'matomoanalytics-chart matomoanalytics-chart-' . $chartType,
Use array

2024-10-30 01:40 UTC, Universal-Omega commented on includes/SpecialAnalytics.php
> +		header( 'Location: ' . SpecialPage::getTitleFor( 'Analytics' )->getFullURL() . '?' . $params['time'] );
Pass query to getFullURL

2024-10-30 01:40 UTC, Universal-Omega commented on includes/SpecialAnalytics.php
> +				$this->msg( 'days' )->params( '1' )->text() => 1,
numParams for this and below

2024-10-30 01:40 UTC, Universal-Omega commented on includes/SpecialAnalytics.php
> +		$period = $this->getContext()->getRequest()->getRawVal( 'period' ) ?? 7;
use getRequest()->getInt( 'period', 7 )

2024-10-30 01:40 UTC, Universal-Omega commented on includes/SpecialAnalytics.php
> +		if ( !is_numeric( $period ) || (int)$period <= 1 || (int)$period > 31 ) {
1) will always be numeric
2) remove type casts

2024-10-30 01:40 UTC, Universal-Omega commented on includes/SpecialAnalytics.php
> +			$period = (int)$period;
Remove else completely as it is useless

2024-10-30 01:40 UTC, Universal-Omega commented on includes/SpecialAnalytics.php
> +			'default' => (int)$period ?? 7,
Only $period no ?? or (int)

2024-10-30 01:42 UTC, Universal-Omega commented on includes/SpecialAnalytics.php
> +		header( 'Location: ' . SpecialPage::getTitleFor( 'Analytics' )->getFullURL() . '?' . $params['time'] );
Also use $this->getOutput()->redirect not header()

2024-10-30 03:22 UTC, AgentIsai commented on modules/ext.matomoanalytics.special.css
First time looking into what CSS even is...

2024-10-30 04:26 UTC, Universal-Omega commented on includes/SpecialAnalytics.php
> -<?php
Moving away from PHP?

2024-10-30 04:28 UTC, Universal-Omega commented on modules/ext.matomoanalytics.special.css
This is not done. You used less format but not .less file.

2024-10-30 04:29 UTC, Universal-Omega commented on includes/SpecialAnalytics.php
> +				$this->msg( 'days' )->numParams( 31 )->parse() => 31,
Options are not defined to parse if you want them to parse it needs to permit that otherwise use ->text() (I don't see a reason to parse here)

2024-10-30 04:31 UTC, Universal-Omega commented on includes/MatomoAnalyticsViewer.php
> +			'class' => 'matomoanalytics-chart matomoanalytics-chart-' . $chartType,
This is not done. If we are using multiple classes, use an array instead of a string to make multille classes more clear.

2024-11-01 19:29 UTC, AgentIsai commented
@coderabbitai review

2024-11-01 19:46 UTC, Universal-Omega commented on .eslintrc.json
> +		"modules/ext.matomoanalytics.charts.js" ],
I'd rather this not be ignored. Then it can never ensure validity.

2024-11-01 19:48 UTC, AgentIsai commented on .eslintrc.json
> +		"modules/ext.matomoanalytics.charts.js" ],
I think it's for the best as its an upstream script.

2024-11-01 19:54 UTC, Universal-Omega commented on .eslintrc.json
> +		"modules/ext.matomoanalytics.charts.js" ],
I'd rather turn off particular rules using comments at the top of the file if absolutely necessary then. Or in an extreme instance if absolutely necessary, turn off all rules with `/* eslint-disable */`

2024-11-01 19:55 UTC, AgentIsai commented on includes/MatomoAnalyticsWiki.php
> +		return $this->getData( 'Actions.getPageUrl', 'range', 'label', 'nb_visits', false, 30, $pageUrl );
This is fine. The function is only used to get the number of visits per 30 days.

2024-11-01 19:57 UTC, AgentIsai commented on .eslintrc.json
> +		"modules/ext.matomoanalytics.charts.js" ],
ESLint needs to be able to parse the file in order to resepect the rule (I know, fun) and since it can't "parse" the file, it doesn't ignore it via `/* eslint-disable */`. This is something temporary at least until its fixed upstream with ChartJS.

2024-11-02 04:41 UTC, AgentIsai commented
coderabbitai review

2024-11-02 04:42 UTC, AgentIsai commented
@coderabbitai review

2024-11-02 13:40 UTC, BlankEclair commented on includes/MatomoAnalyticsWiki.php
> +	public function __construct( $wiki, int $periodSelected = 7 ) {
Type hints?

2024-11-02 13:40 UTC, BlankEclair commented on includes/MatomoAnalyticsWiki.php
> +	private $periodSelected;
Slightly outside the diff range, but why not type hint?

2024-11-02 13:40 UTC, BlankEclair commented on includes/SpecialAnalytics.php
> +		$this->getOutput()->redirect( SpecialPage::getTitleFor( 'Analytics' )->getFullURL( [ 'period' => $params['time'] ] ) );
Kinda ugly when all in one line

2024-11-02 13:40 UTC, BlankEclair commented on modules/ext.matomoanalytics.graphs.js
> +		}
Controllable by CSS (use html.client-nojs and html.client-js)

2024-11-02 13:40 UTC, BlankEclair commented on modules/ext.matomoanalytics.graphs.js
> +	var canvas = fieldset.querySelector('[id^="matomoanalytics-chart"]');
Match based on class instead?

2024-11-02 13:40 UTC, BlankEclair commented on modules/ext.matomoanalytics.special.less
Why so !important?

2024-11-02 13:40 UTC, BlankEclair commented on modules/ext.matomoanalytics.graphs.js
> +	// Initialize empty objects for labels and data
```suggestion
	// Initialize empty arrays for labels and data
```

2024-11-02 13:40 UTC, BlankEclair commented on modules/ext.matomoanalytics.graphs.js
> +			data[label] = value;
Outdated as the variables are now arrays

2024-11-07 20:27 UTC, AgentIsai commented on includes/SpecialAnalytics.php
> +			->show();
This approach is best. Using fn() is not recommended in MediaWiki.

2024-11-07 21:59 UTC, AgentIsai commented on modules/ext.matomoanalytics.special.less
The settings don't take effect otherwise.

2024-11-07 22:04 UTC, AgentIsai commented on includes/MatomoAnalyticsViewer.php
>  			}
The way it currently is is fine. It's a little complex but this is the most it'll get to.

2024-11-08 01:55 UTC, Universal-Omega approved these changes

2024-11-08 01:55 UTC, merged