Do not output HTML comments
miraheze/MatomoAnalytics pull request #50
Opened 2021-05-03 19:26 UTC by R4356th

Are they really necessary? They are currently adding performance overhead.

2021-05-03 19:35 UTC, RhinosF1 approved these changes
I'm 50/50 on how much it's needed but the code is fine.

2021-05-03 19:50 UTC, Universal-Omega commented on includes/MatomoAnalyticsHooks.php
> -				<script type="text/javascript">
Why remove the `<script type="text/javascript">`?

2021-05-03 19:52 UTC, Universal-Omega commented
I don't really think this needs done to be honest. If this does cause performance issues (which I don't personally think it would) it would be extremely minor ones.

2021-05-03 20:17 UTC, R4356th commented on includes/MatomoAnalyticsHooks.php
> -				<script type="text/javascript">
By mistake! Fixed.

2021-05-03 20:17 UTC, Universal-Omega commented on includes/MatomoAnalyticsHooks.php
> -				<script type="text/javascript">
Thanks!

2021-05-03 20:37 UTC, R4356th commented
@RhinosF1 and @Universal-Omega, even removing a single bit of unnecessary code is an improvement. Quoting Ladsgroup from [this upstream task for Vector](https://phabricator.wikimedia.org/T281025), "We are enjoying an effortless and easy and cheap internet connection. Not everyone in the world is so lucky." (Not everyone includes me, too.)

2021-05-03 20:38 UTC, R4356th commented
Anyway, should I do a version bump and update the CHANGELOG now that I have amended this to remove unnecessary ""type="text/javascript""?

2021-05-10 21:23 UTC, R4356th commented
> 
> 
> Anyway, should I do a version bump and update the CHANGELOG now that I have amended this to remove unnecessary ""type="text/javascript""?

Just BOLDly did that.

2021-05-26 19:41 UTC, R4356th commented
Bump. :)

2021-05-26 19:47 UTC, dmehus commented
I //do// agree this is quite a minor commit, but on the whole, I don't see any reason //not// to merge it, since it has no impacts on end users. If anything, it will have a micro positive impact in terms of marginal reduced page load times, I suppose. :+1:

2021-05-26 19:51 UTC, Universal-Omega requested changes

2021-05-26 19:51 UTC, Universal-Omega commented on extension.json
> +	"version": "1.0.6.0",
1.0.5.10

2021-05-26 19:55 UTC, R4356th commented on extension.json
> +	"version": "1.0.6.0",
Done.

2021-05-26 19:59 UTC, Universal-Omega requested changes

2021-05-26 19:59 UTC, Universal-Omega commented on CHANGELOG
> +=== 1.0.5.10 (11-05-2021) ===
Last thing, then I'll merge: change the date to today.

2021-05-26 20:11 UTC, Universal-Omega approved these changes

2021-05-26 20:11 UTC, merged